version: 2

workflows:
  version: 2
  commit:
    jobs:
      - build_and_deploy_prod

jobs:
  build_and_deploy_prod:
    working_directory: ~/repo

    docker:
      - image: circleci/node:10

    environment:
      - CI: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build
          command: |
            npm install
            node src/generator/index.js

      - deploy:
          name: Deploy to aito-grocery-store.api.aito.ai
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash .circleci/upload-to-aito.sh
            fi

      - save_cache:
          paths:
            - ~/bin
            - ~/.awscli
            - ~/.npm
          key: v1-dependencies--{{ checksum "package.json" }}
